config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions: 'users/sessions'
}
  root to: "recipes#index"

  resources :recipes do
    collection do
      get 'search'
    end
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe
  
  validates :material_name, presence: true, if: :required_material?
  validates :quantity, presence: true, if: :required_material?
  
  def required_material?
    recipe&.materials&.index(self)&. < 2
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at id material_name quantity recipe_id updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    ["recipe"]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :cocktail_name, presence: true
  has_many :materials, dependent: :destroy
  accepts_nested_attributes_for :materials
  validates :materials, length: { minimum: 2, message: "は最低でも2つ必要です" }

  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["id", "cocktail_name", "instruction", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["materials"]
  end

  def self.search_material(material_name)
    joins(:materials).where(materials: { name: material_name })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:new, :create]

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'koide' && password == '8258'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_latest_recipes, only: [:new, :index]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    4.times { @recipe.materials.build }
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def search
    @latest_recipes = Recipe.order(created_at: :desc).limit(4)
    @q = Recipe.ransack(params[:q])
    @recipe = @q.result(distinct: true)
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe
      @recipe.destroy
      if Recipe.exists?(id: @recipe.id)
        puts "Recipe with ID #{@recipe.id} was not deleted."
      else
        puts "Recipe with ID #{@recipe.id} was successfully deleted."
      end
      redirect_to root_path
    else
      puts "Recipe with ID #{params[:id]} not found."
      redirect_to root_path, alert: "Recipe not found."
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe.materials.build if @recipe.materials.length < 4
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:cocktail_name, :instruction, materials_attributes: [:id, :material_name, :quantity])
  end
  

  def set_latest_recipes
    @latest_recipes = Recipe.order(created_at: :desc).limit(4)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_before_action :authenticate_user!
  protected

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @recipes = @user.recipes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="footer-section">
      <p>© 2024 COCKTAIL_APP. All Rights Reserved.</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header_contents">
    <div class="log">
      <%= link_to 'COCKTAIL APP', root_path  %>
    </div>

    <div class="user_content">
      <% if user_signed_in? %>
       <div class="user_nav">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'logout-button' %> 
        <%= link_to " #{current_user.nickname}さん", user_path(current_user), class: 'profile-button' %>
       </div>
      <% else %>
       <div class="grid-6">
        <%= link_to "ログイン", new_user_session_path, class: 'login-button' %>
        <%= link_to "新規登録", new_user_registration_path, class: 'register-button' %>
      </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>COCKTAIL_APP</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<div class="page_title">
  <h3>RECIPE CREATE</h3>
</div>

<%= form_with model: @recipe, local: true do |form| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="cocktail_names">
  <%= form.label :cocktail_name, 'カクテル名', class: "cocktail_name" %>
  <%= form.text_field :cocktail_name, class: "cocktail_name_form", value: @recipe.cocktail_name%></div>

  <div id="materials-container">
    <% @recipe.materials.each_with_index do |material, index| %>
      <div class="materials">
        <%= form.label "recipe_material_name_#{index}", '材料', class: "form_name" %>
        <%= form.text_field "materials_attributes[#{index}][material_name]", class: "form", value: material.material_name %>

        <%= form.label "recipe_quantity_#{index}", '分量', class: "form_name"  %>
        <%= form.text_field "materials_attributes[#{index}][quantity]", class: "form", value: material.quantity %>
      </div>
    <% end %>
  </div>
  
  <div class="instruction-container">
    <%= form.label :instruction, '作り方',class: "instruction_name" %>
    <%= form.text_area :instruction,class: "instruction", value: @recipe.instruction %>
  </div>

      <div class="create-container">
    <%= form.submit 'レシピを作成する', class:"create" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>新しいページ</title>
  <%= stylesheet_link_tag 'new_page', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/header' %>
  </header>

    <div class="new-image-container">
      <%= image_tag 'cocktail_recipe.jpg', class: 'new-image' %>
        <div class="new-content">
         <%= render 'form' %>
        </div>
        <div class="button-container">
         <%= link_to 'トップページに戻る', root_path, class: 'return-to-top-button'%>
        </div>
    </div>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</body>
</html>

app/views/recipes/index.html.erb
<header>
  <%= render 'layouts/header' %>
</header>
<div class="image-container">
  <%= image_tag 'assets/cocktail_home.jpg', class: 'cocktail-image' %>
  <div class="text-over-image">癒しのひとときを提供する <br>カクテル検索アプリ</div>
  <div class="button-container">
    <%= link_to 'リキュール検索', search_recipes_path, class: 'button' %>
    <%= link_to 'レシピを追加', new_recipe_path, class: 'button' %>
  </div>
</div>
<footer>
<%= render 'layouts/footer' %>
</footer>

app/views/recipes/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>新しいページ</title>
  <%= stylesheet_link_tag 'new_page', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/header' %>
  </header>

    <div class="new-image-container">
      <%= image_tag 'cocktail_recipe.jpg', class: 'new-image' %>
        <div class="new-content">
         <%= render 'form' %>
        </div>
        <div class="button-container">
         <%= link_to 'トップページに戻る', root_path, class: 'return-to-top-button'%>
        </div>
    </div>
    
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</body>
</html>

app/views/recipes/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>カクテル検索</title>
  <%= stylesheet_link_tag 'search', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/header' %>
  </header>

  <div class="search-image-container">
    <%= image_tag 'cocktail_search.jpg', class: 'search-image' %>
    <div class="search-content">
      <div class="page_title">
      <h3>COCKTAIL SEARCH</h3></div>

      <div class='recipe-contents' id="detailed-search-result-wrapper">
        <%= form_with model: @q, url: search_recipes_path, method: :get, local: true do |f| %>
          <div class="search-field">
            <%= f.label :material_name_cont, 'リキュール名', class: 'search_name' %>
            <br>
            <%= f.text_field :cocktail_name_cont, class: 'search_form'%>
          <%= f.submit '検索', class: 'search_button'%>
          </div>
        <% end %>
        <ul class='recipe-lists' id="detailed-search-result">
          <% @recipe.each do |recipe| %>
            <li class='list'>
              <div class="posted-content">
<%= link_to "#{recipe.cocktail_name}", recipe_path(recipe.id), class: 'cocktail_name' %>

              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

<div class="new-recipe-content">
  <div class="page_title">
    <h4>NEW COCKTAIL</h4>
  </div>
  
  <% @latest_recipes.each_slice(4) do |group| %>
    <div class="recipe-group">
      <% group.each do |recipe| %>
        <div>
          <%= link_to recipe.cocktail_name, recipe_path(recipe), class: 'cocktail_name' %>
          <!-- レシピの詳細へのリンクを表示 -->
        </div>
      <% end %>
    </div>
  <% end %>
</div>



    <div class="button-container">
      <%= link_to 'トップページへ戻る', root_path, class: 'return-to-top-button' %>
    </div>
  </div>


  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</body>
</html>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>カクテルレシピ</title>
  <%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>

<header>
<%= render 'layouts/header' %>
</header>

 <div class="show-image-container">
      <%= image_tag 'cocktail.jpg', class: 'show-image' %>
    <div class="show-content">
      <div class="page_title">  
        <h1><%= @recipe.cocktail_name %></h1>
      </div>
      <div class="materials">
      <h2>材料</h2>
      </div>
      <ul>
<div class="materials-list">
  <% @recipe.materials.each_with_index do |material, index| %>
    <% if index == 2 %>
      </ul> <!-- 最初のulを閉じる -->
      <ul class="horizontal-list"> <!-- 新しいulを追加 -->
    <% end %>
    <li><%= material.material_name %> 　　 <%= material.quantity %></li>
  <% end %>
</ul>



<% if @recipe.instruction.present? %>
  <p><strong class="instruction">作り方</strong></p>
  <p class="instruction_text"><%= @recipe.instruction %></p>
<% end %>
<p class='user_name'>レシピ作成者：<%= link_to @recipe.user.nickname, user_path(@recipe.user) %></p>
<% if user_signed_in? && current_user == @recipe.user %>
  <%= link_to '編集', edit_recipe_path(@recipe), class: 'edit-button' %>
  <%= button_to '削除', recipe_path(@recipe), class: 'delete-button', method: :delete %>
<% end %>

    </div>
<div class="button-container">
  <%= link_to 'ホームへ戻る', root_path , class: 'return-to-top-button'%>
</div>
    </div>

</div>


<footer>
<%= render 'layouts/footer' %>
</footer>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>カクテルレシピ</title>
  <%= stylesheet_link_tag 'user_show', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>

<header>
<%= render 'layouts/header' %>
</header>

<body>
<div class="user-image-container">
    <%= image_tag 'user.jpg', class: 'user-image' %>
      <div class="user-content">
        <div class="page_title">  
          <h1>USER PAGE</h1>
        </div>

        <div class="contents">
            <p class='user_recipe'><%= @nickname %>さんのレシピ一覧</p>
            
            <% @recipes.each_with_index do |recipe, index| %>
              <% if index % 4 == 0 %>
                <div class="recipe-column">
              <% end %>
              
              <p><%= link_to recipe.cocktail_name, recipe_path(recipe), class:'recipes'%></p>
              
              <% if (index + 1) % 4 == 0 || index == @recipes.size - 1 %>
                </div>
              <% end %>
            <% end %>
            
        </div>
      </div>
      <div class="button-container">
          <%= link_to 'ホームへ戻る', root_path , class: 'return-to-top-button'%>
      </div>
</div>
</body>

<footer>
<%= render 'layouts/footer' %>
</footer>
</html>